<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Gestion des erreurs en Python</title>
	<atom:link href="http://sametmax.com/gestion-des-erreurs-en-python/feed/" rel="self" type="application/rss+xml" />
	<link>http://sametmax.com/gestion-des-erreurs-en-python/</link>
	<description>Du code, du cul</description>
	<lastBuildDate>Sat, 07 Nov 2015 11:08:18 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://wordpress.org/?v=4.1</generator>
	<item>
		<title>By: Uggla</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-164878</link>
		<dc:creator><![CDATA[Uggla]]></dc:creator>
		<pubDate>Fri, 16 Oct 2015 15:52:54 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-164878</guid>
		<description><![CDATA[Oh !

Trop la classe, j&#039;ai mon poste sur le site et j&#039;ai trouvé une coquille de maitre SAM ! :)

Comment je suis fier !

Je vais bien souler mes collègues avec ça et m&#039;inspirer de cet article de référence &lt;a href=&quot;http://sametmax.com/le-bon-coup-de-pute-du-jeudi/#tc-comment-title&quot; rel=&quot;nofollow&quot;&gt;http://sametmax.com/le-bon-coup-de-pute-du-jeudi/#tc-comment-title&lt;/a&gt; pour communiquer ma joie.

Plus sérieusement, j&#039;en profite pour vous remercier, super site avec plein de contenu intéressant et avec un un ton pas prise de tête.

J&#039;ai appris plein de trucs grâce à ce site.
]]></description>
		<content:encoded><![CDATA[<p>Oh !</p>
<p>Trop la classe, j&#8217;ai mon poste sur le site et j&#8217;ai trouvé une coquille de maitre SAM ! :)</p>
<p>Comment je suis fier !</p>
<p>Je vais bien souler mes collègues avec ça et m&#8217;inspirer de cet article de référence <a href="http://sametmax.com/le-bon-coup-de-pute-du-jeudi/#tc-comment-title" rel="nofollow">http://sametmax.com/le-bon-coup-de-pute-du-jeudi/#tc-comment-title</a> pour communiquer ma joie.</p>
<p>Plus sérieusement, j&#8217;en profite pour vous remercier, super site avec plein de contenu intéressant et avec un un ton pas prise de tête.</p>
<p>J&#8217;ai appris plein de trucs grâce à ce site.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Sam</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-164877</link>
		<dc:creator><![CDATA[Sam]]></dc:creator>
		<pubDate>Fri, 16 Oct 2015 12:57:56 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-164877</guid>
		<description><![CDATA[&lt;p&gt;Non, tu as parfaitement raison, ma syntaxe n&#039;est plus valide depuis 2.6 il me semble.&lt;/p&gt;
]]></description>
		<content:encoded><![CDATA[<p>Non, tu as parfaitement raison, ma syntaxe n&#8217;est plus valide depuis 2.6 il me semble.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Uggla</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-164870</link>
		<dc:creator><![CDATA[Uggla]]></dc:creator>
		<pubDate>Thu, 15 Oct 2015 21:21:34 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-164870</guid>
		<description><![CDATA[&lt;p&gt;Bonjour,&lt;/p&gt;

&lt;p&gt;Je crois qu&#039;il y a une petite coquille :&lt;/p&gt;

&lt;p&gt;On peut gérer plusieurs exceptions avec un seul bloc :&lt;/p&gt;

&lt;pre lang=&quot;python&quot;&gt;
    try:
        return personnages[100 / i]
        # est exécuté pour ces deux exceptions
    except IndexError, ZeroDivisionError:
        return None
&lt;/pre&gt;

&lt;p&gt;La ligne :&lt;/p&gt;

&lt;pre lang=&quot;python&quot;&gt;

except IndexError, ZeroDivisionError:

&lt;/pre&gt;

&lt;p&gt;devrait être :&lt;/p&gt;

&lt;pre lang=&quot;python&quot;&gt;

except (IndexError, ZeroDivisionError):

&lt;/pre&gt;

&lt;p&gt;D’après la doc ici &lt;a href=&quot;https://docs.python.org/2/tutorial/errors.html#handling-exceptions&quot; rel=&quot;nofollow&quot;&gt;https://docs.python.org/2/tutorial/errors.html#handling-exceptions&lt;/a&gt; :&lt;/p&gt;

&lt;p&gt;A try statement may have more than one except clause, to specify handlers for different exceptions. At most one handler will be executed. Handlers only handle exceptions that occur in the corresponding try clause, not in other handlers of the same try statement. An except clause may name multiple exceptions as a parenthesized tuple, for example:&lt;/p&gt;

&lt;pre lang=&quot;python&quot;&gt;
... except (RuntimeError, TypeError, NameError):
...     pass
&lt;/pre&gt;

&lt;p&gt;Ou j&#039;ai loupé un truc ?&lt;/p&gt;
]]></description>
		<content:encoded><![CDATA[<p>Bonjour,</p>
<p>Je crois qu&#8217;il y a une petite coquille :</p>
<p>On peut gérer plusieurs exceptions avec un seul bloc :</p>

<div class="wp_syntax"><table><tr><td class="code"><pre class="python" style="font-family:monospace;">    <span style="color: #ff7700;font-weight:bold;">try</span>:
        <span style="color: #ff7700;font-weight:bold;">return</span> personnages<span style="color: black;">&#91;</span><span style="color: #ff4500;">100</span> / i<span style="color: black;">&#93;</span>
        <span style="color: #808080; font-style: italic;"># est exécuté pour ces deux exceptions</span>
    <span style="color: #ff7700;font-weight:bold;">except</span> <span style="color: #008000;">IndexError</span><span style="color: #66cc66;">,</span> <span style="color: #008000;">ZeroDivisionError</span>:
        <span style="color: #ff7700;font-weight:bold;">return</span> <span style="color: #008000;">None</span></pre></td></tr></table></div>

<p>La ligne :</p>

<div class="wp_syntax"><table><tr><td class="code"><pre class="python" style="font-family:monospace;">&nbsp;
<span style="color: #ff7700;font-weight:bold;">except</span> <span style="color: #008000;">IndexError</span><span style="color: #66cc66;">,</span> <span style="color: #008000;">ZeroDivisionError</span>:</pre></td></tr></table></div>

<p>devrait être :</p>

<div class="wp_syntax"><table><tr><td class="code"><pre class="python" style="font-family:monospace;">&nbsp;
<span style="color: #ff7700;font-weight:bold;">except</span> <span style="color: black;">&#40;</span><span style="color: #008000;">IndexError</span><span style="color: #66cc66;">,</span> <span style="color: #008000;">ZeroDivisionError</span><span style="color: black;">&#41;</span>:</pre></td></tr></table></div>

<p>D’après la doc ici <a href="https://docs.python.org/2/tutorial/errors.html#handling-exceptions" rel="nofollow">https://docs.python.org/2/tutorial/errors.html#handling-exceptions</a> :</p>
<p>A try statement may have more than one except clause, to specify handlers for different exceptions. At most one handler will be executed. Handlers only handle exceptions that occur in the corresponding try clause, not in other handlers of the same try statement. An except clause may name multiple exceptions as a parenthesized tuple, for example:</p>

<div class="wp_syntax"><table><tr><td class="code"><pre class="python" style="font-family:monospace;">... <span style="color: #ff7700;font-weight:bold;">except</span> <span style="color: black;">&#40;</span><span style="color: #008000;">RuntimeError</span><span style="color: #66cc66;">,</span> <span style="color: #008000;">TypeError</span><span style="color: #66cc66;">,</span> <span style="color: #008000;">NameError</span><span style="color: black;">&#41;</span>:
...     <span style="color: #ff7700;font-weight:bold;">pass</span></pre></td></tr></table></div>

<p>Ou j&#8217;ai loupé un truc ?</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Sam</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-155359</link>
		<dc:creator><![CDATA[Sam]]></dc:creator>
		<pubDate>Fri, 06 Feb 2015 22:39:43 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-155359</guid>
		<description><![CDATA[&lt;p&gt;Il n&#039;y a pas de réponse toute faite. Tu créés tes exceptions en fonction de la manière dont tu veux que ton utilisateur puisse les filtrer. Le seul moyen de faire ça, c&#039;est d&#039;utiliser ta propre lib et de voir ce qui est pratique.&lt;/p&gt;
]]></description>
		<content:encoded><![CDATA[<p>Il n&#8217;y a pas de réponse toute faite. Tu créés tes exceptions en fonction de la manière dont tu veux que ton utilisateur puisse les filtrer. Le seul moyen de faire ça, c&#8217;est d&#8217;utiliser ta propre lib et de voir ce qui est pratique.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Vayel</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-155357</link>
		<dc:creator><![CDATA[Vayel]]></dc:creator>
		<pubDate>Fri, 06 Feb 2015 20:14:27 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-155357</guid>
		<description><![CDATA[Merci pour cet éclairage !

Au niveau des exceptions personnalisées, comment faire ça clairement ? Faut-il créer une exception par message ? Par classe ? Par type (&lt;code&gt;MyValueError&lt;/code&gt;, &lt;code&gt;MyIOError&lt;/code&gt;...) ?
]]></description>
		<content:encoded><![CDATA[<p>Merci pour cet éclairage !</p>
<p>Au niveau des exceptions personnalisées, comment faire ça clairement ? Faut-il créer une exception par message ? Par classe ? Par type (<code>MyValueError</code>, <code>MyIOError</code>&#8230;) ?</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Raito Bezarius</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-155116</link>
		<dc:creator><![CDATA[Raito Bezarius]]></dc:creator>
		<pubDate>Mon, 02 Feb 2015 20:06:32 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-155116</guid>
		<description><![CDATA[Article génial, je connaissais pas le trick du sys.excepthook.

Sinon, y&#039;a un joli moyen de tuer le concept d&#039;exceptions en Python (pour le fuuuun) : FuckIt.py (https://github.com/ajalt/fuckitpy)

Il me semble qu&#039;il parse l&#039;AST pour silencer tous les exceptions (deal with 0/0 now). Enfin, c&#039;est drôle.
]]></description>
		<content:encoded><![CDATA[<p>Article génial, je connaissais pas le trick du sys.excepthook.</p>
<p>Sinon, y&#8217;a un joli moyen de tuer le concept d&#8217;exceptions en Python (pour le fuuuun) : FuckIt.py (<a href="https://github.com/ajalt/fuckitpy" rel="nofollow">https://github.com/ajalt/fuckitpy</a>)</p>
<p>Il me semble qu&#8217;il parse l&#8217;AST pour silencer tous les exceptions (deal with 0/0 now). Enfin, c&#8217;est drôle.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Furankun</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-154214</link>
		<dc:creator><![CDATA[Furankun]]></dc:creator>
		<pubDate>Wed, 21 Jan 2015 14:45:16 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-154214</guid>
		<description><![CDATA[&lt;p&gt;&lt;span class=&quot;merci&quot;&gt;&lt;/span&gt;Super article, merci!&lt;/p&gt;

&lt;p&gt;Quelques typos:&lt;/p&gt;

&lt;p&gt;un motif récurant -&gt; un motif récurrent&lt;/p&gt;

&lt;p&gt;Quand vous attraper -&gt; Quand vous attrapez&lt;/p&gt;

&lt;p&gt;le bloc [...] est appelée -&gt; le bloc [...] est appelé&lt;/p&gt;

&lt;p&gt;gérer toujours l’erreur -&gt; gérez toujours l’erreur (pas sûr pour celle-là, ça dépend de ce que tu veux dire)&lt;/p&gt;

&lt;p&gt;quand vous créé -&gt; quand vous créez&lt;/p&gt;

&lt;p&gt;on a pas la garantie -&gt; on n&#039;a pas la garantie&lt;/p&gt;

&lt;p&gt;ce que vous branler -&gt;  ce que vous branlez&lt;/p&gt;
]]></description>
		<content:encoded><![CDATA[<p><span class="merci"></span>Super article, merci!</p>
<p>Quelques typos:</p>
<p>un motif récurant -&gt; un motif récurrent</p>
<p>Quand vous attraper -&gt; Quand vous attrapez</p>
<p>le bloc [&#8230;] est appelée -&gt; le bloc [&#8230;] est appelé</p>
<p>gérer toujours l’erreur -&gt; gérez toujours l’erreur (pas sûr pour celle-là, ça dépend de ce que tu veux dire)</p>
<p>quand vous créé -&gt; quand vous créez</p>
<p>on a pas la garantie -&gt; on n&#8217;a pas la garantie</p>
<p>ce que vous branler -&gt;  ce que vous branlez</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: cendrieR</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-154209</link>
		<dc:creator><![CDATA[cendrieR]]></dc:creator>
		<pubDate>Wed, 21 Jan 2015 12:16:36 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-154209</guid>
		<description><![CDATA[Merci pour la piqure de rappel.

Je plaide coupable pour : 1. Attraper systématiquement Exception (et logger.exception(e)) ; 2. Préférer checker mes données avec des if plutôt que d&#039; &quot;abuser&quot; des exceptions, je trouve pas ça naturel.

Je vais essayer de me redresser productivement.

Je connaissais pas sys.excepthook, je vais essayer d&#039;utiliser ça pour mes sorties webs. Jusqu&#039;à présent j&#039;utilisais timidement cgi.enable.
]]></description>
		<content:encoded><![CDATA[<p>Merci pour la piqure de rappel.</p>
<p>Je plaide coupable pour : 1. Attraper systématiquement Exception (et logger.exception(e)) ; 2. Préférer checker mes données avec des if plutôt que d&#8217; &#8220;abuser&#8221; des exceptions, je trouve pas ça naturel.</p>
<p>Je vais essayer de me redresser productivement.</p>
<p>Je connaissais pas sys.excepthook, je vais essayer d&#8217;utiliser ça pour mes sorties webs. Jusqu&#8217;à présent j&#8217;utilisais timidement cgi.enable.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Sam</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-154200</link>
		<dc:creator><![CDATA[Sam]]></dc:creator>
		<pubDate>Wed, 21 Jan 2015 09:17:33 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-154200</guid>
		<description><![CDATA[&lt;p&gt;Ca va dépendre de l&#039;exception. Pour ValueError, y pas de raison d&#039;attraper un message plutôt qu&#039;un autre. Si tu dois faire ça, c&#039;est probablement que le try est mal positionné.&lt;/p&gt;

&lt;p&gt;Pour IOError par contre, c&#039;est plus compliqué : en 2.7, oui tu dois checker e.errno. En Python 3, le problème a été résolu en ajouter de nouvelles exceptions : https://docs.python.org/3/library/exceptions.html#os-exceptions&lt;/p&gt;
]]></description>
		<content:encoded><![CDATA[<p>Ca va dépendre de l&#8217;exception. Pour ValueError, y pas de raison d&#8217;attraper un message plutôt qu&#8217;un autre. Si tu dois faire ça, c&#8217;est probablement que le try est mal positionné.</p>
<p>Pour IOError par contre, c&#8217;est plus compliqué : en 2.7, oui tu dois checker e.errno. En Python 3, le problème a été résolu en ajouter de nouvelles exceptions : <a href="https://docs.python.org/3/library/exceptions.html#os-exceptions" rel="nofollow">https://docs.python.org/3/library/exceptions.html#os-exceptions</a></p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Blef</title>
		<link>http://sametmax.com/gestion-des-erreurs-en-python/#comment-154193</link>
		<dc:creator><![CDATA[Blef]]></dc:creator>
		<pubDate>Wed, 21 Jan 2015 07:51:54 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=15786#comment-154193</guid>
		<description><![CDATA[Super article !

De mon côté il y a un truc que je ne sais pas faire correctement je pense. Il peut arriver qu&#039;un ValueError par exemple soit levé avec un message &lt;em&gt;A&lt;/em&gt; ou avec un message &lt;em&gt;B&lt;/em&gt;. Et dans certains cas je veux que le message &lt;em&gt;A&lt;/em&gt; soit attrapé et non bloquant et le message B je veux qu&#039;il ne le soit pas. Donc ce que je fais en général c&#039;est un :

&lt;code&gt;

try:

pass

except ValueError, e:

if e.message == &#039;A&#039;:

OK

else:

raise

&lt;/code&gt;

Sauf que j&#039;ai vu, je ne sais plus où qu&#039;il ne faut pas utiliser le e.message. Du coup il faut utiliser le e.errno ? Ou il y a un autre moyen plus conseillé ?
]]></description>
		<content:encoded><![CDATA[<p>Super article !</p>
<p>De mon côté il y a un truc que je ne sais pas faire correctement je pense. Il peut arriver qu&#8217;un ValueError par exemple soit levé avec un message <em>A</em> ou avec un message <em>B</em>. Et dans certains cas je veux que le message <em>A</em> soit attrapé et non bloquant et le message B je veux qu&#8217;il ne le soit pas. Donc ce que je fais en général c&#8217;est un :</p>
<p><code></p>
<p>try:</p>
<p>pass</p>
<p>except ValueError, e:</p>
<p>if e.message == 'A':</p>
<p>OK</p>
<p>else:</p>
<p>raise</p>
<p></code></p>
<p>Sauf que j&#8217;ai vu, je ne sais plus où qu&#8217;il ne faut pas utiliser le e.message. Du coup il faut utiliser le e.errno ? Ou il y a un autre moyen plus conseillé ?</p>
]]></content:encoded>
	</item>
</channel>
</rss>
